# Official channels of free-license / CC artists. (id, name, license, url, focus_bias)
CHANNELS = [
 ("UCgrQkWWf_48rQm-x-dQ4_uA","PeriTune","CC BY 4.0","https://peritune.com/", 50),
 ("UCKt5TenSalOze024ONgcF4g","Steven O'Brien","CC BY 4.0","https://www.steven-obrien.net/", 50),
 ("UCSZXFhRIx6b0dFX3xS8L1yQ","Kevin MacLeod","CC BY 4.0","https://incompetech.com/", 50),
 ("UCw4wdHksXbaiyu3BiBNNW0w","Alexander Nakarada","CC BY 4.0","https://www.creatorchords.com/", 50),
 ("UCgWj4VcD_U7-9LhGXRGEpSg","Visager","CC BY 4.0","https://visager.bandcamp.com/", 20),
 ("UCvNnyy0_KxpJegpv3ytVM5Q","魔王魂 (森田交一)","Free with attribution (maou.audio terms)","https://maou.audio/", 50),
 ("UCNPMwbX6-SclEmvFX5_ihCw","H/MIX GALLERY (秋山裕和)","Free with attribution (hmix.net terms)","http://www.hmix.net/", 50),
 ("UCQ3NFBxvp8IBeu7B39wUVuA","Tim Beek","Free with attribution (timbeek.com)","https://timbeek.com/", 40),
 ("UCDGnOsTBqehvJxW-uSYPEMQ","Patrick de Arteaga","CC BY 4.0","https://patrickdearteaga.com/", 30),
 ("UCUuUqWLLsUjheuYkP9AWxTA","Scott Buckley","CC BY 4.0","https://www.scottbuckley.com.au/", 30),
 ("UCEj6A1Wf5k31DzH-93zBTMQ","Chris Zabriskie","CC BY 4.0","https://chriszabriskie.com/", 30),
 ("UCbNEKbBPYTHMLS1aPm9LhpA","Lee Rosevere","CC BY 4.0","https://leerosevere.bandcamp.com/", 30),
 ("UCN4bhxAz0GUg98Yuqr8hRTA","Kai Engel","CC BY 4.0","https://www.kai-engel.com/", 30),
 ("UCtgf00GvfFQVsYBA7V7RwUw","TeknoAXE","CC BY 4.0","https://teknoaxe.com/", 40),
 ("UCGxVX35l9Tbd10OJTj-isqw","Aaron Krogh","Free with attribution","https://soundcloud.com/aaron-anderson-11", 30),
 ("UCsLlqLIE-TqDq3lh5kU2PeA","HeatleyBros","Free with attribution","https://www.heatleybros.com/", 30),
 ("UCQKGLOK2FqmVgVwYferltKQ","Ross Bugden","Free with attribution","https://www.youtube.com/@RossBugden", 20),
 ("UCIbpHW0vqun4y7V9bPKLxqw","Loyalty Freak Music / Komiku","CC0","https://loyaltyfreakmusic.com/", 40),
 ("UCq15_9MvmxT1r2-LLjtkokg","DOVA-SYNDROME (official)","Free (DOVA-SYNDROME license)","https://dova-s.jp/", 40),
 ("UCQuMmwxT25MPI1E0YXwARhA","MusMus","Free with attribution (musmus.main.jp)","https://musmus.main.jp/", 40),
 ("UCxLKyBhC6igFhLEb0gxvQNg","Sappheiros","CC BY 3.0","https://soundcloud.com/sappheirosmusic", 20),
 ("UCxmng6_DMIayDwkiWGVzVRQ","Alexandr Zhelanov","CC BY 3.0/4.0","https://soundcloud.com/alexandr-zhelanov", 30),
 ("UCE3yg1sjKJvHLz3GlSrPiOw","Darren Curtis","Free with attribution","https://www.darrencurtismusic.com/", 30),
 ("UC3M9CX5HWSw25k5QL3FkDEA","Punch Deck","CC BY 4.0","https://punchdeck.bandcamp.com/", 20),
 ("UCAerMM15hr8nVRHJqQ1SlYw","Meydän","CC BY 4.0","https://meydan.bandcamp.com/", 20),
 ("UCfSUheoljDlGDjerRylO4Nw","Vindsvept","Free with attribution (non-commercial)","https://vindsvept.bandcamp.com/", 40),
 ("UCjMZjGhrFq_4llVS_x2XJ_w","Derek & Brandon Fiechter","Free with attribution (non-commercial)","https://www.youtube.com/@Fiechters", 40),
 ("UCwXHymx4a60WVzgM-Lde0rw","Sergey Cheremisinov","CC BY 4.0","https://www.cheremisinov.com/", 20),
 ("UC6mnTEE6xP74YcZDpkKGy-A","Eric Matyas (Soundimage.org)","Free with attribution","https://soundimage.org/", 40),
 ("UCemEB1ueDZM-wz2sv7Rh7qA","Eric Skiff","CC BY 3.0","https://ericskiff.com/music/", 10),
 ("UCSkZR_TwiLSY1X2DO60MZLg","PANICPUMPKIN (みそか)","Free with attribution (panicpumpkin terms)","https://pansound.com/panicpumpkin/", 30),
]
CHANNELS2 = [
 ("UCAnL5FcWSSa29e_U5FZCglg","Senses Circuit","Free with attribution (senses-circuit.com)","https://www.senses-circuit.com/", 40),
 ("UCNH3lgz5OzW2Fl576CVuRIg","SHW (Hamashio) 和風","Free with attribution (shw.in)","http://shw.in/", 30),
 ("UCj7ws5TMe7QLvAs89y2mB2A","ハヤシユウ","Free (DOVA-SYNDROME license)","https://dova-s.jp/", 30),
 ("UCfjca6Z_wpyinTqHdIYJ49Q","しゃろう (Sharou)","Free (DOVA-SYNDROME license)","https://dova-s.jp/", 20),
 ("UCDEEWU5e7_6RdwtYMSYbE5g","騒音のない世界 (Noiseless World)","Free with attribution","https://noiselessworld.net/", 30),
 ("UCDtlRqNHJIqrx3KcNk-OD_w","Nihilore","CC BY 4.0","https://www.nihilore.com/", 30),
 ("UCk1LInPwXosJGnXQQuwC4Xw","Ben Burnes (Abstraction)","Free with attribution","https://abstractionmusic.com/", 30),
 ("UC8zvP72p9bGC1xHEtVjyy-g","Matthew Pablo","CC BY 3.0","https://matthewpablo.com/", 20),
 ("UColXhU3J1W6lAF8DzdnKwSw","cynicmusic (Alex Smith)","CC0 / CC BY","https://cynicmusic.com/", 20),
 ("UC6eZomtc5U8jzArDoqh62xw","Trevor Lentz","CC BY 3.0","https://opengameart.org/users/trevor-lentz", 20),
 ("UC3_tcjJS_a1NpDpYaCCTwcw","Kyatto","Free with attribution","https://www.youtube.com/@Kyatto", 30),
 ("UCVGlh-cE3dOwy5VodIv4mcA","Bit By Bit Sound","Free with attribution","https://bitbybitsound.com/", 30),
 ("UC8gIl1OvjMOzFKuoRmLKm0g","Zander Noriega (Topic)","CC BY 3.0","https://opengameart.org/users/zander-noriega", 15),
 ("UCqpsCBnOq_E-4lofm2FEQAg","Snabisch (Topic)","Free with attribution","https://snabisch.itch.io/", 20),
 ("UCuafV9Sni-EA8ndccsni_pg","Ozzed (Topic)","CC BY 4.0","https://ozzed.net/", 15),
 ("UCiZrrHOyr_SHWYpYlJeUnZw","Audionautix / Jason Shaw (Topic)","CC BY 4.0","https://audionautix.com/", 20),
 ("UC_bOmZPILFBUceBYIS8ewXA","Twin Musicom (Topic)","CC BY 4.0","https://www.twinmusicom.org/", 20),
]
